languageCode: en-us
baseurl: http://innoki.github.io/dogs
title: ""

publishdir: public

permalinks:
  destination: /dest/:slug

disableRSS: true
disableSitemap: true

params:
  FacebookURL: https://www.facebook.com/TeamInnoki
  TwitterURL: https://twitter.com/teaminnoki?lang=de
  GitHubURL: https://github.com/innoki
  ImprintURL: http://innoki.de/?page_id=305

  CatsBaseURL: https://example.com/cats
